def ope():
    a=int(input("Enter the first number: "))
    b=int(input("Enter the Second number: "))
    print("\n---  OPERATORS  ---")
    print("Addition:", a + b)
    print("Substraction", a - b)
    print("Multiplication", a * b)
    print("Division", a / b)
    print("Floor Division", a // b)
    print("Remainder:",a % b)
    print("Power:", a ** 2)
    print("a > b:",a > b)
    print("a == b:", a == b)
    print("Logical:", a > 10 and b < 10)
    print("20 in list:", 20 in[10, 20 ,30])
